server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: warehouse-ms-backend
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 5000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/warehouse-ms-backend?characterEncoding=utf-8&useSSL=false

