package com.lyx.warehouse;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn

/**
 * @author lyx
 */
@SpringBootApplication
public class WarehouseMsBackendApplication {

    public static void main(String[] args) {
        SpringApplication.run(WarehouseMsBackendApplication.class, args);
    }

}
